apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ai-platform
  labels:
    app: api
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: ai-devops-platform-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: ghcr.io/hubertlim/ai-devops-platform-lab/api:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: APP_ENV
            - name: AI_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: AI_PROVIDER
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability:4317"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
