apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-platform

resources:
  - namespace.yaml
  - api-serviceaccount.yaml
  - api-configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: kustomize
